name: Test Mod Build on PR

on:
  pull_request:
    branches:
      - '**/prod'
      - '**/dev'

jobs:
  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper & Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Test Data Generation
        run: ./gradlew runData

      - name: Run Test Build
        run: ./gradlew build