name : Send Discord Test Message

on :
  workflow_dispatch :

jobs :
  send_msg :
    name : Send Message
    runs-on : ubuntu-latest
    steps :
      - name : Notify Discord Server
        uses : appleboy/discord-action@v1.1.0
        with :
          webhook_id : ${{ secrets.DISCORD_ID }}
          webhook_token : ${{ secrets.DISCORD_TOKEN }}
          color : "#088c7d"
          username : "Maykr Bot"
          message : "
          # :package: Foobar Test
          
          **Download**
          Foobar
            
          ##Changelog
          foobar
          @Numen
          "
